### ISSUE TITLE
Add Support For Abstraction Over `AuthnWithProvider`

### ISSUE THREAD

**Issue by LuisOsta** [knox-networks/knox-ts#3]

**Comment by LuisOsta** [comment]
As part of this we'll also update to `ed25519-keygen` to 0.4.1 which has the fix for the cryptography problems

**Comment by fkim7** [comment]
We also need to add https://buf.build/knox-networks/user-mgmt/docs/main:user_api.v1#user_api.v1.UserApiService.HandleOIDCCallback

since AuthnWithProvider is a 2 part call.  
flow example can be seen here https://www.notion.so/Rosalind-Tech-Sprint-92292ada3b33450088ccfff6767a1bb6?pvs=4#f74601175c9a4214b8d4f0b45fd6ccbc
